const $=s=>document.querySelector(s), storageKey='farmatime-medications-v1', takenKey='farmatime-taken-v1';
let meds=JSON.parse(localStorage.getItem(storageKey)||'[]'), taken=JSON.parse(localStorage.getItem(takenKey)||'{}'), timer;
const today=new Date(); const pad=n=>String(n).padStart(2,'0'); const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; const dateLabel=d=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(d).replace('.','');
function save(){localStorage.setItem(storageKey,JSON.stringify(meds));localStorage.setItem(takenKey,JSON.stringify(taken));}
function dates(m){const out=[];let d=new Date(`${m.start}T00:00:00`),end=new Date(`${m.end}T00:00:00`);while(d<=end){out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function dosesFor(m,d){let day=Math.floor((new Date(`${iso(d)}T00:00:00`)-new Date(`${m.start}T00:00:00`))/86400000);if(day<0||iso(d)>m.end)return[];if(m.type==='interval'){let a=[],start=m.firstTime,first=+start.split(':')[0]*60 + +start.split(':')[1],step=+m.hours*60;for(let k=-1;k<=day*24+24;k++){let minutes=first+k*step;if(Math.floor(minutes/1440)===day)a.push({time:`${pad(Math.floor(minutes%1440/60))}:${pad(minutes%60)}`,dose:m.dose})}return a.sort((x,y)=>x.time.localeCompare(y.time))}if(m.type==='daily')return[{time:m.time,dose:m.dose}];let cursor=0;for(const s of m.steps){if(day<cursor+s.days)return[{time:m.time,dose:s.dose}];cursor+=s.days}return[]}
function allDoses(m,d){return dosesFor(m,d).map((x,i)=>({...x,key:`${m.id}-${iso(d)}-${x.time}-${i}`,date:iso(d)}))}
function render(){const list=$('#medList'),empty=$('#emptyState');list.innerHTML='';empty.style.display=meds.length?'none':'block';const nowDay=iso(today);let total=0,completed=0;meds.forEach(m=>{const card=document.createElement('article');card.className='med-card card';card.style.setProperty('--med-color',m.color);let todayDoses=allDoses(m,today);let times=todayDoses.map(x=>`<span class="dose-time ${taken[x.key]?'done':''}"><b>${x.time}</b>${x.dose} ${x.dose==1?'comprimido':'comprimidos'}</span>`).join('');total+=todayDoses.length;completed+=todayDoses.filter(x=>taken[x.key]).length;card.innerHTML=`<div class="med-top"><div class="med-ident"><i class="med-dot"></i><div><div class="med-name">${escapeHtml(m.name)}</div><div class="med-dose">${labelType(m)}</div></div></div><button class="med-menu" data-edit="${m.id}" aria-label="Editar ${escapeHtml(m.name)}">···</button></div><div class="med-dates">${dateLabel(new Date(`${m.start}T00:00:00`))} — ${dateLabel(new Date(`${m.end}T00:00:00`))}</div><div class="dose-times">${times||'<span class="med-dose">No hay toma programada hoy</span>'}</div>`;card.addEventListener('click',e=>{if(e.target.closest('[data-edit]'))openModal(m)});list.append(card)});let pct=total?Math.round(completed/total*100):0;$('#progressNumber').textContent=pct+'%';$('#progressRing').style.background=`conic-gradient(var(--violet) ${pct*3.6}deg,#ececf3 0deg)`;$('#progressTitle').textContent=total?`${completed} de ${total} tomas completadas`:'Todo listo para hoy';$('#progressText').textContent=total?(pct===100?'Has completado todas las tomas de hoy.':'Marca las tomas desde esta tarjeta cuando las completes.'):'Añade medicamentos para ver tus tomas.';updateNext();}
function labelType(m){if(m.type==='interval')return`1 toma cada ${m.hours} horas · ${m.dose} ${m.dose==1?'comprimido':'comprimidos'}`;if(m.type==='daily')return`1 toma diaria · ${m.dose} ${m.dose==1?'comprimido':'comprimidos'}`;return`Pauta descendente · ${m.steps.map(s=>s.dose).join(' → ')} comprimidos`}
function updateNext(){let now=new Date(), candidates=[];for(const m of meds)for(let offset=0;offset<Math.max(1,dates(m).length);offset++){let d=new Date(now);d.setDate(d.getDate()+offset);for(const x of allDoses(m,d)){let at=new Date(`${x.date}T${x.time}:00`);if(at>=now&&!taken[x.key])candidates.push({...x,m,at})}if(candidates.length)break}candidates.sort((a,b)=>a.at-b.at);let n=candidates[0];if(!n){$('#nextDoseName').textContent=meds.length?'No quedan tomas pendientes':'Añade tu primer medicamento';$('#nextDoseMeta').textContent=meds.length?'Buen trabajo por hoy.':'Configura una pauta para empezar a organizarte';$('#nextCountdown').textContent='—';return}$('#nextDoseName').textContent=n.m.name;$('#nextDoseMeta').textContent=`${n.dose} ${n.dose==1?'comprimido':'comprimidos'} · ${n.at.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}`;$('#nextCountdown').textContent=n.at.toDateString()===now.toDateString()?'a las '+n.time:n.at.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setDates(){const s=$('#startDate'),e=$('#endDate');if(!s.value){s.value=iso(today);let end=new Date(today);end.setDate(end.getDate()+4);e.value=iso(end)}}
function addStep(step={dose:1,days:1}){const row=document.createElement('div');row.className='step-row';row.innerHTML=`<label class="field">Dosis<input class="step-dose" type="number" min="0.25" step="0.25" value="${step.dose}"><small>comprimidos</small></label><label class="field">Duración<input class="step-days" type="number" min="1" value="${step.days}"><small>días</small></label><button type="button" class="remove-step" aria-label="Quitar tramo">×</button>`;row.querySelector('.remove-step').onclick=()=>row.remove();$('#taperSteps').append(row)}
function openModal(m=null){$('#modalBackdrop').hidden=false;setDates();$('#deleteButton').hidden=!m;if(m){$('#modalTitle').textContent='Editar medicamento';$('#medId').value=m.id;$('#medName').value=m.name;$('#medColor').value=m.color;$('#startDate').value=m.start;$('#endDate').value=m.end;$('#scheduleType').value=m.type;$('#intervalHours').value=m.hours||8;$('#intervalDose').value=m.dose||1;$('#firstTime').value=m.firstTime||'08:00';$('#dailyDose').value=m.dose||1;$('#dailyTime').value=m.time||'08:00';$('#taperTime').value=m.time||'08:00';$('#taperSteps').innerHTML='';(m.steps||[{dose:2,days:3},{dose:1,days:3},{dose:.5,days:2}]).forEach(addStep)}else{$('#medForm').reset();$('#medId').value='';$('#taperSteps').innerHTML='';addStep({dose:2,days:3});addStep({dose:1,days:3});addStep({dose:.5,days:2});setDates()}toggleSchedule()}
function closeModal(){$('#modalBackdrop').hidden=true}function toggleSchedule(){['intervalFields','dailyFields','taperFields'].forEach(id=>$('#'+id).hidden=$('#scheduleType').value!==id.replace('Fields',''))}
$('#addButton').onclick=()=>openModal();$('#emptyAddButton').onclick=()=>openModal();$('#closeModal').onclick=closeModal;$('#cancelButton').onclick=closeModal;$('#scheduleType').onchange=toggleSchedule;$('#addStep').onclick=()=>addStep();$('#medColor').oninput=e=>$('#colorPreview').style.background=e.target.value;$('#deleteButton').onclick=()=>{const id=$('#medId').value,m=meds.find(x=>x.id===id);if(!m||!confirm(`¿Eliminar ${m.name} de tu tratamiento?`))return;meds=meds.filter(x=>x.id!==id);Object.keys(taken).filter(k=>k.startsWith(`${id}-`)).forEach(k=>delete taken[k]);save();closeModal();render();showToast('Medicamento eliminado')};
$('#medForm').onsubmit=e=>{e.preventDefault();const type=$('#scheduleType').value,m={id:$('#medId').value||crypto.randomUUID(),name:$('#medName').value.trim(),color:$('#medColor').value,start:$('#startDate').value,end:$('#endDate').value,type};if(new Date(m.end)<new Date(m.start)){showToast('La fecha de fin debe ser posterior al inicio');return}if(type==='interval')Object.assign(m,{hours:+$('#intervalHours').value,dose:+$('#intervalDose').value,firstTime:$('#firstTime').value});if(type==='daily')Object.assign(m,{dose:+$('#dailyDose').value,time:$('#dailyTime').value});if(type==='taper')Object.assign(m,{time:$('#taperTime').value,steps:[...document.querySelectorAll('.step-row')].map(r=>({dose:+r.querySelector('.step-dose').value,days:+r.querySelector('.step-days').value}))});const i=meds.findIndex(x=>x.id===m.id);i<0?meds.push(m):meds[i]=m;save();closeModal();render();showToast('Medicamento guardado')};
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),3000)}
$('#notificationsButton').onclick=async()=>{if(!('Notification'in window)){showToast('Este navegador no admite notificaciones');return}const permission=await Notification.requestPermission();showToast(permission==='granted'?'Avisos activados en este dispositivo':'No se han activado los avisos');if(permission==='granted'){$('.status-dot').style.background='#48bf89';if('serviceWorker'in navigator)navigator.serviceWorker.ready.then(r=>r.showNotification('FarmaTime',{body:'Los recordatorios están activados.'}))}};
function checkNotifications(){if(!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date();meds.forEach(m=>allDoses(m,now).forEach(d=>{const at=new Date(`${d.date}T${d.time}:00`),noticeKey=`notice-${d.key}`;if(Math.abs(at-now)<30000&&!localStorage.getItem(noticeKey)){new Notification(`Hora de ${m.name}`,{body:`${d.dose} ${d.dose==1?'comprimido':'comprimidos'} · ${d.time}`,icon:'icon.svg',tag:d.key});localStorage.setItem(noticeKey,'1')}}))}
document.addEventListener('click',e=>{const dose=e.target.closest('.dose-time');if(!dose)return;const card=dose.closest('.med-card'),m=meds.find(x=>x.name===card.querySelector('.med-name').textContent);if(!m)return;const dayDoses=allDoses(m,today),match=dayDoses.find(x=>dose.textContent.includes(x.time));if(match){taken[match.key]=!taken[match.key];save();render();showToast(taken[match.key]?'Toma marcada como realizada':'Toma desmarcada')}});
const dn=new Intl.DateTimeFormat('es-ES',{weekday:'long'}).format(today);$('#todayName').textContent=dn.toUpperCase();$('#todayDate').textContent=new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(today).replace('.','');$('#colorPreview').style.background=$('#medColor').value;render();timer=setInterval(()=>{updateNext();checkNotifications()},30000);checkNotifications();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
